apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-app-rules
  labels:
    role: prometheus-rulefiles
    prometheus: prometheus
spec:
  groups:
  - name: app.rules
    rules:
    - alert: App Alert
      expr: sum(container_cpu_cfs_periods_total) < 3
